### ISSUE TITLE
UML sequence diagrams

### ISSUE THREAD

**Issue by RiedSmith** [RiedSmith/Group-12#20]
Each member write a sequence diagram for 3 user stories each

**Comment by Lance-Ly** [comment]
I have finished all of the buyer's UML sequence diagrams

**Comment by brentts** [comment]
Finished all of guest sequence diagrams

**Comment by Pdom02** [comment]
Finished all of the Seller UML Sequence diagrams

**Comment by RiedSmith** [comment]
Finished admin UML sequence diagrams
